pihole_local_backup: host_vars/android-pihole/pihole-backup-teleporter.tar.gz

pihole_webpassword: 'CLTmi5'

pihole_webtheme:           'default-light'
pihole_pihole_interface:   'wlan0'
pihole_pihole_dns_1:       '8.8.8.8'
pihole_pihole_dns_2:       '8.8.4.4'

pihole_query_logging:         'false'
pihole_install_web_server:    'true'
pihole_install_web_interface: 'true'
pihole_lighttpd_enabled:      'true'
pihole_cache_size:            '10000'

  # PIHOLE_INTERFACE=wlan0
  # PIHOLE_DNS_1=8.8.8.8
  # PIHOLE_DNS_2=8.8.4.4
  # QUERY_LOGGING=false
  # INSTALL_WEB_SERVER=true
  # INSTALL_WEB_INTERFACE=true
  # LIGHTTPD_ENABLED=true
  # CACHE_SIZE=10000
  # DNS_FQDN_REQUIRED=true
  # DNS_BOGUS_PRIV=true
  # DNSMASQ_LISTENING=local
  # WEBPASSWORD=5ed10d02d34697140baea020d9cf4043d1ee08e26d187fa289f726cd19b8cbde
  # BLOCKING_ENABLED=true
  # WEBUIBOXEDLAYOUT=boxed
  # WEBTHEME=default-light
